import { Injectable } from '@angular/core';
import { videos } from '../shared/models/video';

@Injectable({
  providedIn: 'root',
})
export class VideoService {
  constructor() {}
  getVideoById(id: number): videos {
    return this.getAllVideo().find((video) => video.id == id)!;
  }
  getAllVideo(): videos[] {
    return [
      {
        id: 1,
        thumbnail: 'assets/img/video2.mp4',
        img: 'assets/img/logo1.png',
        title:
          'Build Spotify Blockchain Web3 dApp with Next.js, Phantom, QuickNode & Digital Ocean',
        side_title: 'Mr Bean In The Snow & Cold | Mr Bean Cartoon World',
        subtitle: 'YouTube Clone',
        side_subtitle: 'Mr Bean Cartoon',
        timestamp: '10M Views.3 Months Ago',
        like_icon: 'material-icons-outlined',
        liked_icon_name: 'thumb_up',
        dislike_icon: 'material-icons-outlined',
        disliked_icon_name: 'thumb_down',
        like: 0,
        dislike: 'DISLIKE',
        share_icon: 'material-icons reply',
        share_icon_name: 'reply',
        share_name: 'SHARE',
        more_icon: 'material-icons-outlined',
        more_icon_name: 'more_horiz',
        subscriber: '5.0M subscribers',
        subscribe: 'SUBSCRIBE',
        subscribed: 'SUBSCRIBED',
        verify_icon: 'material-icons',
        verify_icon_name: 'check_circle',
      },
      {
        id: 2,
        thumbnail: 'assets/img/video2.mp4',
        img: 'assets/img/angular.png',
        title:
          'This is a angular tutorial for beginners. Best programming language to learn.',
        side_title: 'Mr Bean In The Snow & Cold | Mr Bean Cartoon World',
        subtitle: 'Angular Tutorial',
        side_subtitle: 'Mr Bean Cartoon',
        timestamp: '50M Views.6 Months Ago',
        like_icon: 'material-icons-outlined',
        liked_icon_name: 'thumb_up',
        dislike_icon: 'material-icons-outlined',
        disliked_icon_name: 'thumb_down',
        like: 0,
        dislike: 'DISLIKE',
        share_icon: 'material-icons reply',
        share_icon_name: 'reply',
        share_name: 'SHARE',
        more_icon: 'material-icons-outlined',
        more_icon_name: 'more_horiz',
        subscriber: '5.04M subscribers',
        subscribe: 'SUBSCRIBE',
        subscribed: 'SUBSCRIBED',
        verify_icon: 'material-icons',
        verify_icon_name: 'check_circle',
      },
      {
        id: 3,
        thumbnail: 'assets/img/video2.mp4',
        img: 'assets/img/html.png',
        title:
          'Make A Complete Website Using HTML and CSS, Complete HTML and CSS Multiple Pages Website Design Tutorial Step by Step',
        side_title: 'Mr Bean In The Snow & Cold | Mr Bean Cartoon World',
        subtitle: 'Programming Language',
        side_subtitle: 'Mr Bean Cartoon',
        timestamp: '10M Views.3 Months Ago',
        like_icon: 'material-icons-outlined',
        liked_icon_name: 'thumb_up',
        dislike_icon: 'material-icons-outlined',
        disliked_icon_name: 'thumb_down',
        like: 0,
        dislike: 'DISLIKE',
        share_icon: 'material-icons reply',
        share_icon_name: 'reply',
        share_name: 'SHARE',
        more_icon: 'material-icons-outlined',
        more_icon_name: 'more_horiz',
        subscriber: '2.04M subscribers',
        subscribe: 'SUBSCRIBE',
        subscribed: 'SUBSCRIBED',
        verify_icon: 'material-icons',
        verify_icon_name: 'check_circle',
      },
      {
        id: 4,
        thumbnail: 'assets/img/video2.mp4',
        img: 'assets/img/harry.jpeg',
        title:
          'Make a WordPress Website | Wordpress Tutorial for Beginners | Elementor Tutorial In Hindi',
        side_title: 'Mr Bean In The Snow & Cold | Mr Bean Cartoon World',
        subtitle: 'CodeWithHarry',
        side_subtitle: 'Mr Bean Cartoon',
        timestamp: '11,602 views Jun 30, 2022',
        like_icon: 'material-icons-outlined',
        liked_icon_name: 'thumb_up',
        dislike_icon: 'material-icons-outlined',
        disliked_icon_name: 'thumb_down',
        like: 0,
        dislike: 'DISLIKE',
        share_icon: 'material-icons reply',
        share_icon_name: 'reply',
        share_name: 'SHARE',
        more_icon: 'material-icons-outlined',
        more_icon_name: 'more_horiz',
        subscriber: '5.7M subscribers',
        subscribe: 'SUBSCRIBE',
        subscribed: 'SUBSCRIBED',
        verify_icon: 'material-icons',
        verify_icon_name: 'check_circle',
      },
      {
        id: 5,
        thumbnail: 'assets/img/video2.mp4',
        img: 'assets/img/mosh.jpeg',
        title:
          ' Python tutorial - Python full course for beginners - Go from Zero to Hero with Python',
        side_title: 'Mr Bean In The Snow & Cold | Mr Bean Cartoon World',
        subtitle: ' Programming with Mosh',
        side_subtitle: 'Mr Bean Cartoon',
        timestamp: '10M Views.3 Months Ago',
        like_icon: 'material-icons-outlined',
        liked_icon_name: 'thumb_up',
        dislike_icon: 'material-icons-outlined',
        disliked_icon_name: 'thumb_down',
        like: 0,
        dislike: 'DISLIKE',
        share_icon: 'material-icons reply',
        share_icon_name: 'reply',
        share_name: 'SHARE',
        more_icon: 'material-icons-outlined',
        more_icon_name: 'more_horiz',
        subscriber: '1.59M subscribers',
        subscribe: 'SUBSCRIBE',
        subscribed: 'SUBSCRIBED',
        verify_icon: 'material-icons',
        verify_icon_name: 'check_circle',
      },
      {
        id: 6,
        thumbnail: 'assets/img/video2.mp4',
        img: 'assets/img/thapa.jpeg',
        title:
          'create a Complete Responsive Website using HTML, CSS & JAVASCRIPT in Hindi.',
        side_title: 'Mr Bean In The Snow & Cold | Mr Bean Cartoon World',
        subtitle: 'Thapa Technical ',
        side_subtitle: 'Mr Bean Cartoon',
        timestamp: '44,733 views  May 9, 2022',
        like_icon: 'material-icons-outlined',
        liked_icon_name: 'thumb_up',
        dislike_icon: 'material-icons-outlined',
        disliked_icon_name: 'thumb_down',
        like: 0,
        dislike: 'DISLIKE',
        share_icon: 'material-icons reply',
        share_icon_name: 'reply',
        share_name: 'SHARE',
        more_icon: 'material-icons-outlined',
        more_icon_name: 'more_horiz',
        subscriber: '3.04M subscribers',
        subscribe: 'SUBSCRIBE',
        subscribed: 'SUBSCRIBED',
        verify_icon: 'material-icons',
        verify_icon_name: 'check_circle',
      },
    ];
  }
}
